default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production: &production
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DATABASE_POOL"] || 5 %>
  timeout: 1000

staging:
  <<: *production