env: &default
  secret_key_base:   <%= ENV["SECRET_KEY_BASE"] %>
  hostname:          <%= ENV["APP_HOSTNAME"] %>
  fog_accesskey:     <%= ENV["GCS_ACCESSKEY"] %>
  fog_secretkey:     <%= ENV["GCS_SECRETKEY"] %>
  fog_directory:     <%= ENV["GCS_DIRECTORY"] %>
  vk_key:            <%= ENV["VK_KEY"] %>
  vk_secret:         <%= ENV["VK_SECRET"] %>
  googleplus_key:    <%= ENV["GOOGLE_KEY"] %>
  googleplus_secret: <%= ENV["GOOGLE_SECRET"] %>
  mail_from:         <%= ENV["MAIL_FROM"] %>
  mail_user:         <%= ENV["MAIL_USER"] %>
  mail_password:     <%= ENV["MAIL_PASSWORD"] %>

development:
  <<: *default
  secret_key_base: 7d941f99c44ec0e3eb0a5674d3b924f38f2b6b35448d83eaec21b6139b956366b4c7d82a4acf45d35bcf88e866978b5a9caaae8148498bb2f7bae3e8921543b3

test:
  <<: *default
  secret_key_base: 0230d98a39d5c3026b1507503b29af7fdee7598ab0178f94a7ac55a92e50acc94b006be45b42dbd7994e9ac898acbcc0c4f5d9e6afbc418dd4dddfc5551b6628

production:
  <<: *default

staging:
  <<: *default
